import bisect

delimiter = " - "
print()
print("------ instantiating ------")
print("[3, 5, 7, 11]", delimiter, [3, 5, 7, 11])
print("[1] + [0] * 10", delimiter, [1] + [0] * 10)
print("list(range(30))", delimiter, list(range(30)))
print()
print("------ basic operations ------")
A = [0, 11, 21, 31, 2]
print("A = [0, 1, 2, 3, 4]")
print("len(A)", delimiter, len(A))
A.append(42)
print("A.append(42)", delimiter, A)
A.remove(2)
print("A.remove(2)", delimiter, A)
A.insert(3, 28)
print("A.insert(3, 28)", delimiter, A)
print("min(A)", delimiter, min(A))
print("max(A)", delimiter, max(A))
print()
print("------ bitsec ------")
A = list(range(10))
print("A = list(range(10))")
print("bisect.bisect_left(A, 5)", delimiter, bisect.bisect_left(A, 5))
print("bisect.bisect_right(A, 5)", delimiter, bisect.bisect_right(A, 5))
print("bisect.bisect(A, 5)", delimiter, bisect.bisect(A, 5))
print()
print("A = [5, 4, 6, 3, 7, 2, 8, 0, 9, 1]")
print("reversed(A)", delimiter, reversed(A))
print("list(reversed(A))", delimiter, list(reversed(A)))
print()
